In [1]:
import numpy as np

## 58 Introduction to numpy

What is numpy?
 numpy is kind of data with series of numbers of algorithm works on it
 numpy contains in data analysis
 
Why numpy?
  numerical calculation
  large amount of data calculation
  it's fast
  vectorization via broadcasting(avoiding loops)
  backbone of other python scientific packages
  

## 60 numpy data types and attributes

In [7]:
import numpy as np

### data types and attributes

In [8]:
# numpy's main datatype is ndarray
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [9]:
type(a1)

numpy.ndarray

In [12]:
a2=np.array([[1,2.7,3]
            ,[4,5,6.5]])

a3=np.array([[[1,2,3],[4,5,6],[7,8,9]], [[10,11,12],[13,14,15],[16,17,18]]])

In [13]:
a2

array([[1. , 2.7, 3. ],
       [4. , 5. , 6.5]])

In [14]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [15]:
a1.shape # 

(3,)

In [16]:
a2.shape

(2, 3)

In [18]:
a3.shape# shape of array

(2, 3, 3)

In [19]:
a1.ndim,a2.ndim,a3.ndim # dimensions

(1, 2, 3)

In [21]:
a1.dtype,a2.dtype,a3.dtype # data types of array numbers

(dtype('int32'), dtype('float64'), dtype('int32'))

In [22]:
a1.size,a2.size,a3.size # size of array

(3, 6, 18)

In [24]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [25]:
# create dataframe from numpy array
import pandas as pd
df2=pd.DataFrame(a2)
df2

0    1    2
0  1.0  2.7  3.0
1  4.0  5.0  6.5

# 61 creating numpy array

## 2. creating array

In [26]:
sample_array=np.array([1,2,3])
sample_array

array([1, 2, 3])

In [27]:
sample_array.dtype

dtype('int32')

In [30]:
ones=np.ones((2,3))  # array filled with ones
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [31]:
type(ones)

numpy.ndarray

In [33]:
zeros=np.zeros((2,3)) # arrays with zeros
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [39]:
rang_array=np.arange(0,10,2)
rang_array

array([0, 2, 4, 6, 8])

In [42]:
ramdom_array=np.random.randint(0,10,size=(3,5))
ramdom_array

array([[4, 5, 3, 6, 6],
       [1, 1, 8, 6, 0],
       [7, 8, 4, 7, 2]])

In [43]:
ramdom_array.size

15

In [47]:
ramdom_array.shape

(3, 5)

In [49]:
rd_2=np.random.random((5,3))
rd_2

array([[0.9524382 , 0.73614552, 0.51757056],
       [0.97275834, 0.04057393, 0.15012893],
       [0.33499849, 0.35140466, 0.77456852],
       [0.12029684, 0.42180443, 0.23227027],
       [0.27492411, 0.48902595, 0.85350938]])

In [50]:
rd_2.shape

(5, 3)

In [56]:
rd_3=np.random.rand(5,3)
rd_3

array([[0.52188932, 0.25049668, 0.94890227],
       [0.3400677 , 0.11785955, 0.18465194],
       [0.61639588, 0.83391411, 0.85008954],
       [0.41331929, 0.38452562, 0.03430115],
       [0.68340242, 0.11865086, 0.82093079]])

In [55]:
# sudorandom numbers
np.random.seed()

# 62 numpy random seed

In [57]:
# pseudo random numbers
np.random.seed()

In [58]:
rd_4=np.random.randint(10,size=(5,3))
rd_4

array([[0, 7, 9],
       [2, 8, 5],
       [3, 0, 7],
       [9, 2, 6],
       [3, 8, 4]])

In [59]:
rd_4.shape

(5, 3)

In [62]:
# pseudo random numbers And seed put random number as it is not changable
np.random.seed(seed=0)
rd_5=np.random.randint(10,size=(5,3))
rd_5

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [66]:
# pseudo random numbers And seed put random number as it is not changable
#np.random.seed(seed=7)
rd_5=np.random.randint(10,size=(5,3))
rd_5

array([[9, 6, 4],
       [9, 7, 3],
       [3, 8, 3],
       [0, 1, 0],
       [0, 6, 7]])

In [69]:
rd_5=np.random.random((5,3)) # changable number

rd_5

array([[0.64911885, 0.55741353, 0.86853158],
       [0.14362802, 0.44790435, 0.65923332],
       [0.6617098 , 0.83856663, 0.53255759],
       [0.03964609, 0.09559835, 0.79889497],
       [0.40238848, 0.68245195, 0.50192349]])

# 63 viewing arrays and matrices

In [72]:
np.unique(rd_4)

array([0, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
a1

array([1, 2, 3])

In [74]:
a2

array([[1. , 2.7, 3. ],
       [4. , 5. , 6.5]])

In [75]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [76]:
a1[0]

1

In [79]:
a2[0] # gives fist array or row

array([1. , 2.7, 3. ])

In [80]:
a3.shape

(2, 3, 3)

In [82]:
a3[0] # gives first array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
a3[0][0]

array([1, 2, 3])

In [84]:
a2[1] # 2nd row 

array([4. , 5. , 6.5])

In [85]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [86]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [90]:
a3[:1,:2,:3]

array([[[1, 2, 3],
        [4, 5, 6]]])

In [91]:
a4=np.random.randint(10,size=(2,3,4,5))
a4

array([[[[5, 4, 4, 9, 9],
         [0, 6, 2, 6, 8],
         [2, 4, 1, 6, 1],
         [5, 1, 6, 9, 8]],

        [[6, 5, 9, 7, 5],
         [4, 9, 6, 8, 1],
         [5, 5, 8, 3, 7],
         [7, 9, 4, 7, 5]],

        [[9, 6, 2, 0, 5],
         [3, 0, 5, 7, 1],
         [8, 4, 9, 0, 2],
         [0, 7, 6, 2, 9]]],


       [[[9, 5, 1, 0, 0],
         [9, 1, 1, 5, 3],
         [2, 0, 4, 8, 7],
         [1, 4, 9, 3, 6]],

        [[7, 1, 0, 2, 7],
         [0, 0, 9, 8, 2],
         [0, 5, 5, 0, 9],
         [0, 8, 4, 5, 1]],

        [[4, 0, 7, 2, 0],
         [3, 9, 8, 3, 7],
         [1, 0, 1, 4, 6],
         [1, 0, 1, 0, 1]]]])

In [92]:
a4.shape,a4.ndim

((2, 3, 4, 5), 4)

In [96]:
a4[0][2][0]

array([9, 6, 2, 0, 5])

In [101]:
# 1st 4 number of innermost
a4[:,:,:,:4]

array([[[[5, 4, 4, 9],
         [0, 6, 2, 6],
         [2, 4, 1, 6],
         [5, 1, 6, 9]],

        [[6, 5, 9, 7],
         [4, 9, 6, 8],
         [5, 5, 8, 3],
         [7, 9, 4, 7]],

        [[9, 6, 2, 0],
         [3, 0, 5, 7],
         [8, 4, 9, 0],
         [0, 7, 6, 2]]],


       [[[9, 5, 1, 0],
         [9, 1, 1, 5],
         [2, 0, 4, 8],
         [1, 4, 9, 3]],

        [[7, 1, 0, 2],
         [0, 0, 9, 8],
         [0, 5, 5, 0],
         [0, 8, 4, 5]],

        [[4, 0, 7, 2],
         [3, 9, 8, 3],
         [1, 0, 1, 4],
         [1, 0, 1, 0]]]])

In [100]:
# 1st 4 number of innermost
a4[:,:,:,:1]

array([[[[5],
         [0],
         [2],
         [5]],

        [[6],
         [4],
         [5],
         [7]],

        [[9],
         [3],
         [8],
         [0]]],


       [[[9],
         [9],
         [2],
         [1]],

        [[7],
         [0],
         [0],
         [0]],

        [[4],
         [3],
         [1],
         [1]]]])