# dot product vs element wise

In [2]:
import numpy as np

In [3]:
a1=np.array([1,2,3])
a2=np.array([[1,2.7,3]
            ,[4,5,6.5]])
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]], [[10,11,12],[13,14,15],[16,17,18]]])

## dot product

In [4]:
np.random.seed(0)

mat1=np.random.randint(10,size=(5,3))
mat2=np.random.randint(10,size=(5,3))
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [5]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [7]:
mat1.shape,mat2.shape

((5, 3), (5, 3))

In [9]:
mat1*mat2 # multiplicatio of two matrix element wise

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [11]:
np.multiply(mat1,mat2) # using function

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [12]:
# dot product

np.dot(mat1,mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [13]:
# http://matrixmultiplication.xyz/

In [14]:
mat1.T

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]])

In [16]:
mat2.shape,mat1.T.shape

((5, 3), (3, 5))

In [18]:
mat3=np.dot(mat2,mat1.T)
mat3

array([[ 51, 130,  67, 115, 111],
       [ 55,  76,  39,  69,  77],
       [ 72, 164,  85, 146, 145],
       [ 20,  33,  27,  37,  56],
       [ 15,  44,  34,  47,  64]])

In [19]:
mat3.shape

(5, 5)

# 69 Exercise: nut buttor  store sales

## dot product example  nut butter sales

In [21]:
np.random.seed(0)

sales_amt=np.random.randint(20,size=(5,3))
sales_amt

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [23]:
# create weekly sales dataframe
import pandas as pd

weekly_sales=pd.DataFrame(sales_amt,index=['mon','tue','wed','thu','fri'],
                         columns=['almond butter','penut butter','cashew butter'])
weekly_sales

almond butter  penut butter  cashew butter
mon             12            15              0
tue              3             3              7
wed              9            19             18
thu              4             6             12
fri              1             6              7

In [24]:
# create prices
prices=np.array([10,8,12])
prices

array([10,  8, 12])

In [26]:
prices.shape

(3,)

In [28]:
# creating data frame
butter_prices=pd.DataFrame(prices.reshape(1,3),index=['Prices'],columns=['almond butter','penut butter','cashew butter'])
butter_prices

almond butter  penut butter  cashew butter
Prices             10             8             12

In [31]:
total_sale=prices.dot(sales_amt)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [33]:
total_sale=prices.dot(sales_amt.T)
total_sale

array([240, 138, 458, 232, 142])

In [35]:
# create daily sales
butter_prices

almond butter  penut butter  cashew butter
Prices             10             8             12

In [36]:
weekly_sales

almond butter  penut butter  cashew butter
mon             12            15              0
tue              3             3              7
wed              9            19             18
thu              4             6             12
fri              1             6              7

In [38]:
butter_prices.shape,weekly_sales.shape

((1, 3), (5, 3))

In [39]:
daily_sale=butter_prices.dot(weekly_sales.T)

In [40]:
daily_sale

mon  tue  wed  thu  fri
Prices  240  138  458  232  142

In [41]:
weekly_sales

almond butter  penut butter  cashew butter
mon             12            15              0
tue              3             3              7
wed              9            19             18
thu              4             6             12
fri              1             6              7

In [46]:
weekly_sales["total"]=total_sale

In [47]:
weekly_sales

almond butter  penut butter  cashew butter  total
mon             12            15              0    240
tue              3             3              7    138
wed              9            19             18    458
thu              4             6             12    232
fri              1             6              7    142

In [48]:
weekly_sales["total"]=daily_sale.T

In [49]:
weekly_sales

almond butter  penut butter  cashew butter  total
mon             12            15              0    240
tue              3             3              7    138
wed              9            19             18    458
thu              4             6             12    232
fri              1             6              7    142

# 70 Comparision operators

In [4]:
a1

array([1, 2, 3])

In [5]:
a2

array([[1. , 2.7, 3. ],
       [4. , 5. , 6.5]])

In [6]:
a1>a2

array([[False, False, False],
       [False, False, False]])

In [7]:
a2>a1

array([[False,  True, False],
       [ True,  True,  True]])

In [8]:
a1>=a2

array([[ True, False,  True],
       [False, False, False]])

In [10]:
bool_a=a1>=a2
bool_a

array([[ True, False,  True],
       [False, False, False]])

In [12]:
type(bool_a),bool_a.dtype

(numpy.ndarray, dtype('bool'))

In [13]:
a1>5

array([False, False, False])

In [14]:
a1<5

array([ True,  True,  True])

In [15]:
a1==a1

array([ True,  True,  True])

In [16]:
a1==a2

array([[ True, False,  True],
       [False, False, False]])

# 71 Sorting arrays

In [20]:
import numpy as np
rd_a=np.random.randint(10,size=(3,5))
rd_a

array([[4, 2, 5, 2, 9],
       [1, 6, 2, 3, 4],
       [5, 3, 7, 4, 3]])

In [21]:
rd_a.shape

(3, 5)

In [22]:
rd_a

<function ndarray.sort>

In [24]:
np.sort(rd_a)  # sort array

array([[2, 2, 4, 5, 9],
       [1, 2, 3, 4, 6],
       [3, 3, 4, 5, 7]])

In [26]:
np.argsort(rd_a) # sort the indices

array([[1, 3, 0, 2, 4],
       [0, 2, 3, 4, 1],
       [1, 4, 3, 0, 2]], dtype=int64)

In [27]:
np.argsort(a1)

array([0, 1, 2], dtype=int64)

In [28]:
np.argmin(a1)

0

In [29]:
np.argmax(a1)

2

In [30]:
rd_a

array([[4, 2, 5, 2, 9],
       [1, 6, 2, 3, 4],
       [5, 3, 7, 4, 3]])

In [31]:
np.argmax(rd_a)

4

In [32]:
np.argmax(rd_a,axis=0) # vertically /column  index values of max no.

array([2, 1, 2, 2, 0], dtype=int64)

In [33]:
np.argmax(rd_a,axis=1) # horizontally /row index values ofmax no.

array([4, 1, 2], dtype=int64)

#  72 turn images into numpy arrays

In [52]:
import matplotlib.pyplot as plt
#plt.show("fig1.png")

In [65]:
< img src="images/pandas.png" />

SyntaxError: invalid syntax (<ipython-input-65-ee5a6311a4b1>, line 1)

In [59]:
from matplotlib.image import imread

In [60]:
panda=imread("D://Software//pooja_2//Python_complte_certificate.jpg")

ValueError: Only know how to handle PNG; with Pillow installed, Matplotlib can handle more images